#!/usr/bin/env python

import os
import sys

import git
import urllib


REPO_ROOT = '/home/eyqs/Downloads/Dropbox/Projects/web/'
REPO_REMOTE = 'origin'
BUILD_BRANCH = 'gh-pages'
BUILD_FOLDER = '_site/'



def archive():

    pages = ['', 'about/', 'blog/', 'cakes/', 'documents/', 'projects/',
             'questions/', 'resume/', 'sitemap/', 'tools/']

    posts = ['1804-ubcs-cpen/', '1805-late-rides/', '1806-wtfjs-idkjs/',
             '1807-cloud-next/', '1808-sunny-vale/', '1809-mug-share/',
             '1811-music-18w1/', '1901-new-year/', '1902-wand-earth/']

    for page in pages:
        print('Archiving page: ' + page)
        urllib.request.urlopen('http://web.archive.org/save/' +
                               'https://eyqs.ca/' + page)

    for post in posts:
        print('Archiving post: ' + post)
        urllib.request.urlopen('http://web.archive.org/save/' +
                               'https://eyqs.ca/blogs/' + post)


def push():

    repo = git.Repo(REPO_ROOT)
    repo.git.subtree('push', REPO_REMOTE, BUILD_BRANCH, prefix=BUILD_FOLDER)



if __name__ == '__main__':

    if len(sys.argv) != 2:
        print('Usage: ./web [archive|push]')
        exit(1)

    os.chdir(REPO_ROOT)
    if sys.argv[1] == 'archive':
        archive()
    elif sys.argv[1] == 'push':
        push()
