#!/usr/bin/env python3

import os
import sys

import git
import urllib.request


SITE_URL = 'https://eyqs.ca'
REPO_REMOTE = 'origin'
BUILD_BRANCH = 'gh-pages'

REPO_ROOT = '/home/eugeneyqshen/web'
BUILD_FOLDER = '_site'
BLOG_FOLDER = 'blog'

ARCHIVE_URL = 'http://web.archive.org/save'
ARCHIVED_PAGES = ['about', 'blog', 'cakes', 'documents', 'sitemap']
ARCHIVED_POSTS = ['2001-first-post', '2002-ubcs-cpen', '2003-japn-trans']



def archive():

    print('Archiving index')
    urllib.request.urlopen(f'{ARCHIVE_URL}/{SITE_URL}/')

    for page in ARCHIVED_PAGES:
        page_url = f'{SITE_URL}/{page}'
        print(f'Archiving page: {page}')
        urllib.request.urlopen(f'{ARCHIVE_URL}/{page_url}/')

    for post in ARCHIVED_POSTS:
        post_url = f'{SITE_URL}/{BLOG_FOLDER}/{post}'
        print(f'Archiving post: {post}')
        urllib.request.urlopen(f'{ARCHIVE_URL}/{post_url}/')



def push():

    repo = git.Repo(REPO_ROOT)
    repo.git.push(REPO_REMOTE)
    repo.git.subtree('push', REPO_REMOTE, BUILD_BRANCH, prefix=BUILD_FOLDER)



def bad_input():
    print('Usage: ./web [archive|push]')
    exit(1)



if __name__ == '__main__':

    if len(sys.argv) != 2:
        bad_input()

    os.chdir(REPO_ROOT)
    if sys.argv[1] == 'archive':
        archive()
    elif sys.argv[1] == 'push':
        push()
    else:
        bad_input()
