#!/usr/bin/env python3

import os
import sys
import urllib.request

import git


repo_root = None
src_dir = None
SITE_URL = 'https://eyqs.ca'
ARCHIVE_URL = 'http://web.archive.org/save'
PREAMBLE_SEPARATOR = '---\n'
INDEX_FILE = 'index.html'
TOOLS_LAYOUT = 'layout: tool\n'
PREAMBLES = {
        'avalon': {'title': 'Tiny Avalon'},
        'chess': {'title': 'Tiny Chess', 'json': './manifest.json'},
        'cit': {'title': 'The Cartographically Imbricating Transformer'},
        'req': {'title': 'The UBC Prereq Tree'},
        'track': {'title': 'Tiny Tracker'},
}



def get_name(name):
    return os.path.splitext(name)[0]

def strip_repo_root(path):
    return os.path.relpath(path, repo_root)

def archive_url(rel_url):
    if rel_url and not rel_url.endswith('/'):
        rel_url += '/'
    urllib.request.urlopen(f'{ARCHIVE_URL}/{SITE_URL}/{rel_url}')
    return f'{SITE_URL}/{rel_url}'


def print_progress(message, func):
    print(f'{message}...', end='\r', flush=True)
    output = func()
    if type(output) == tuple:
        output = output[0]
    print(f'{message}: {output.strip()}', flush=True)


def reset_submodules():
    os.chdir(repo_root)
    repo = git.Repo(repo_root)
    for submodule in repo.submodules:
        submodule.update(init=True)
        submodule.module().head.reset(index=True, working_tree=True)
    return f'{strip_repo_root(src_dir)}/'


def archive():

    with os.scandir(src_dir) as it:
        for entry in it:
            if entry.is_dir():
                if os.path.exists(os.path.join(entry.path, 'index.html')):
                    rel_url = get_name(strip_repo_root(entry.path))
                    print_progress('Archiving page',
                            lambda: archive_url(rel_url))


def build():

    with os.scandir(src_dir) as it:
        for entry in it:
            if entry.is_dir():
                content = []

                content.append(PREAMBLE_SEPARATOR)
                content.append(TOOLS_LAYOUT)
                for key, value in PREAMBLES[entry.name].items():
                    content.append(f'{key}: {value}\n')
                content.append(f'css: ./{entry.name}.css\n')
                content.append(PREAMBLE_SEPARATOR)

                file_path = os.path.join(entry.path, INDEX_FILE)
                print('Overwriting tools page...', end='\r', flush=True)

                with open(file_path, 'r') as f:
                    in_body = False
                    for line in f:
                        if line.strip() == '</body>':
                            break
                        if in_body:
                            content.append(line)
                        if line.strip() == '<body>':
                            in_body = True

                with open(file_path, 'w') as f:
                    for line in content:
                        f.write(line.replace('./', '{{ url }}'))
                print('Overwriting tools page: '
                        + os.path.relpath(file_path, repo_root))


def clean():

    print_progress('Resetting submodules', reset_submodules)



def bad_input():
    print('Usage: ./web [archive|build|clean] [repo_root] [src_dir]')
    exit(1)

if __name__ == '__main__':

    if len(sys.argv) != 4:
        bad_input()

    repo_root = sys.argv[2]
    src_dir = sys.argv[3]
    if sys.argv[1] == 'archive':
        archive()
    elif sys.argv[1] == 'build':
        build()
    elif sys.argv[1] == 'clean':
        clean()
    else:
        bad_input()
